### ISSUE TITLE
Invalid audio

### ISSUE THREAD

**Issue by fundies** [dubhater/D2VWitch#1]
I get an invalid audio file when trying to dump from a vob with pcm audio. mpv / mplayer are unable to play it even after renaming to .wav. However, DGIndex gives me a valid file.

http://low.awesome-toons.org/temp/ED3.MPG

[greg@greg-desktop ED3]$ mediainfo ED3.d2v\ Ta0\ 0\ channels\ 1536\ kbps.audio 
General
Complete name                            : ED3.d2v Ta0 0 channels 1536 kbps.audio
File size                                        : 13.2 MiB

[greg@greg-desktop ED3]$ mediainfo ED3\ Ta0\ 48K\ 16bit\ 2ch.wav 
General
Complete name                            : ED3 Ta0 48K 16bit 2ch.wav
Format                                   : Wave
File size                                : 13.2 MiB
Duration                                 : 1mn 12s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 536 Kbps

Audio
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, Sign                    : Signed
Codec ID                                 : 1
Duration                                 : 1mn 12s
Bit rate mode                            : Constant
Bit rate                                 : 1 536 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Stream size                              : 13.2 MiB (100%)

**Comment by dubhater** [comment]
It's not invalid, it just doesn't have a header.

What if I made it write PCM audio in Wave64 format? Would that work for you?

**Comment by fundies** [comment]
Proabably. I'd just like to be able to open/play the wavs with other programs. Currently I have to use dgindex instead

**Comment by dubhater** [comment]
On second thought, the file does contain more than just the raw audio samples (so it's invalid). Anyway, Wave64 output is done. I'll just polish it a bit and push it tomorrow.
