### ISSUE TITLE
Cannot run without a display device

### ISSUE THREAD

**Issue by rzumer** [dubhater/D2VWitch#3]
On Debian Jessie, with no display device, the following error is displayed when attempting to run D2VWitch v2 from the command line: 
```bash
QXcbConnection: Could not connect to display
Aborted
```
It seems to occur regardless of any command line options, so I assume it involves the logic for displaying the graphical user interface. If so, would it be possible to add an option at compilation and/or launch time to disable any graphical elements?

**Comment by dubhater** [comment]
Maybe I'll make Qt optional at compile time. In the meantime, the best I can offer is a workaround: add the option ``-platform offscreen`` to every invocation of d2vwitch.

**Comment by rzumer** [comment]
That workaround does seem to work with input and output files set correctly, thank you for the information.

**Comment by dubhater** [comment]
Found a nicer solution.
