### ISSUE TITLE
Glitched Display

### ISSUE THREAD

**Issue by rlaphoenix** [dubhater/D2VWitch#4]
For some reason when I create a D2V using this program, it fails occassionally, skips frames, rewinds frames, and just generally desyncs and fails to render at times.

![https://i.imgur.com/d6Fv6Ok.png](https://i.imgur.com/d6Fv6Ok.png)

It doesn't occur if I run DGIndex.exe through latest wine on Arch Linux.
The only downside is that I have to open the generated d2v and replace the windows style path to a linux style path.

I attached below the 2 d2v's, one created by d2vwitch, and one created by dgindex, both using default settings, both created from an mpg extracted via Inviska

[d2vs.zip](https://github.com/dubhater/D2VWitch/files/3590424/d2vs.zip)

It also seems to exhibit a mis-match with VapourSynthEditor. The frames dont match up, when using the D2VWitch d2v, it finishes about 20 or so odd frames before VapourSynthEditor says it should, whereas the DGIndex d2v ends at the right time.

**Comment by dubhater** [comment]
Can you provide the first 10 MB of this mpg, please? You can use dd:
```sh
dd if=original.mpg of=beginning.mpg bs=1M count=10
```

**Comment by rlaphoenix** [comment]
[beginning.zip](https://github.com/dubhater/D2VWitch/files/3591383/beginning.zip)

**Comment by dubhater** [comment]
Good news! I fiiiinally figured it out and fixed it.

**Comment by rlaphoenix** [comment]
That's fantastic news, I'm curious what caused it?

**Comment by dubhater** [comment]
My bad decisions, probably. :) I added code to calculate the audio delays, which made use of some older code that wasn't implemented correctly. The new code has side effects.
