### ISSUE TITLE
--audio-ids aborts with 'std::out_of_range' error

### ISSUE THREAD

**Issue by yesimanoob** [dubhater/D2VWitch#8]
Using v5 (x64 Windows binary) from github, `--audio-ids <track #>` fails for track that exists.

First, verify that track exists (matches mediainfo and dgindex report).
```
d2vwitch --info Test.ts
Input file(s):
    D:\Test.ts

    Type: MPEG-TS (MPEG-2 Transport Stream)

Video tracks:
    Id: 111, type: MPEG-2 video, 1440x1080, yuv420p

Audio tracks:
    Id: 112, type: AAC (Advanced Audio Coding), 183 kbps, stereo, 48000 Hz
    Id: 113, type: AAC (Advanced Audio Coding), 215 kbps, stereo, 48000 Hz
```

Attempt to extract, but fail.
```
d2vwitch --audio-ids 112 Test.ts
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted
```
Same results with `0x112`.

Interestingly, it succeeds with `all`.

**Comment by yesimanoob** [comment]
Note: Am able to demux the single audio track in the GUI without issue.

**Comment by dubhater** [comment]
Thanks for the report. I found the problem.
